all: score_graph print_point

score_graph: score_graph.o 
	g++ -o score_graph score_graph.o
print_point: print_point.o
	g++ -o print_point print_point.o
score_graph.o: score_graph.cc
	g++ -c score_graph.cc
print_point.o: print_point.cc
	g++ -c print_point.cc
clean:
	rm score_graph print_point score_graph.o print_point.o
